In [15]:
import pandas as pd
import json
import os
import re

In [16]:
pickle_files = [
    "./data/sonnet3.pkl",
    "./data/gpt-4o-3.pkl",
    "./data/gemini-1.5-pro-3.pkl",
]

dfs = [pd.read_pickle(file) for file in pickle_files]
df = pd.concat(dfs)

df

,image_path,num_points,num_intersections,line_colors,line_thickness,model_output_raw,extracted_number,is_correct,Model
0,image_0_thickness_2.png,3,1,"[red, blue]",2,The blue and red lines intersect at one point ...,1,True,Sonnet
1,image_0_thickness_3.png,3,1,"[red, blue]",3,The blue and red lines intersect at one point ...,1,True,Sonnet
2,image_0_thickness_4.png,3,1,"[red, blue]",4,The blue and red lines intersect once in the i...,1,True,Sonnet
3,image_1_thickness_2.png,3,2,"[red, blue]",2,The blue and red lines intersect once in the i...,1,False,Sonnet
4,image_1_thickness_3.png,3,2,"[red, blue]",3,"In the given image, the blue and red lines int...",1,False,Sonnet
...,...,...,...,...,...,...,...,...,...
145,image_48_thickness_3.png,3,2,"[red, blue]",3,The blue and red lines intersect **twice**. \n,2,True,Gemini-1.5-Pro
146,image_48_thickness_4.png,3,2,"[red, blue]",4,The blue and red lines intersect **twice**. \n,2,True,Gemini-1.5-Pro
147,image_49_thickness_2.png,3,0,"[red, blue]",2,The blue and red lines do not intersect in the...,0,True,Gemini-1.5-Pro
148,image_49_thickness_3.png,3,0,"[red, blue]",3,The blue and red lines intersect **zero** time...,0,True,Gemini-1.5-Pro
149,image_49_thickness_4.png,3,0,"[red, blue]",4,The blue and red lines do not intersect in the...,0,True,Gemini-1.5-Pro

In [17]:
accuracy_per_model_and_word = df.groupby(["Model"])["is_correct"].mean()

# Convert the accuracy to percentage and print the result
accuracy_per_model_and_word = accuracy_per_model_and_word * 100
# round 2 decimal places
accuracy_per_model_and_word = accuracy_per_model_and_word.round(2)

print(accuracy_per_model_and_word.T)

Model
Gemini-1.5-Pro    77.33
Sonnet            49.33
gpt-4o            46.31
Name: is_correct, dtype: float64

Model
Gemini-1.5-Pro    77.33
Sonnet            49.33
gpt-4o            46.31
Name: is_correct, dtype: float64

In [19]:
# Group by both Model and line_thickness
accuracy_per_model_thickness = df.groupby(["Model", "line_thickness"])[
    "is_correct"
].mean()

# Convert the accuracy to percentage
accuracy_per_model_thickness = accuracy_per_model_thickness * 100
# Round to 2 decimal places
accuracy_per_model_thickness = accuracy_per_model_thickness.round(2)

print(accuracy_per_model_thickness)

Model           line_thickness
Gemini-1.5-Pro  2                 74.00
                3                 76.00
                4                 82.00
Sonnet          2                 42.00
                3                 52.00
                4                 54.00
gpt-4o          2                 42.86
                3                 50.00
                4                 46.00
Name: is_correct, dtype: float64

Model           line_thickness
Gemini-1.5-Pro  2                 74.00
                3                 76.00
                4                 82.00
Sonnet          2                 42.00
                3                 52.00
                4                 54.00
gpt-4o          2                 42.86
                3                 50.00
                4                 46.00
Name: is_correct, dtype: float64